### ISSUE TITLE
using angular combine with directive tags

### ISSUE THREAD

**Issue by thdotnet** [astik/angular-combine#5]
Hi, I'm using directives like:

```
return {
            restrict: 'E',
            templateUrl: function (element, attr) {
            	return 'App/components/shared/cart/cart.html';
            },
            controller: 'cart.controller',
            controllerAs: 'cart',
            link: function (scope, element, attrs) {

            }
        };
```

and in my html I'll use:

`<cart></cart>`

I was wondering, can I use angular combine to bundle html files in this case?

**Comment by astik** [comment]
No problem with that.
You can combine all your component / directive templates into a single HTML file. It's working without problem (so far) on any of my project =)

**Comment by thdotnet** [comment]
do you have a sample using directives like mine? I'm not sure how to use this with directives like mine...

**Comment by astik** [comment]
You have nothing to do especially for directive ... it works the same way as for the controller.
Angular-combine just wrap the template retrieving at a low level of Angular system. That means that every time a template is needed, angular-combine can be used.
When asking for template from a directive or from a component, it is the same thing as when asking from a controller or a route.
I just have uploaded a demo for a component : https://github.com/astik/angular-combine/commit/892b1907c7c67e47ff258ae21d395a5d297a3f03

**Comment by thdotnet** [comment]
fantastic! thank you @astik
